## Stage 1 : build with maven builder image with native capabilities
# Alpine Linux with JDK
FROM quay.io/quarkus/centos-quarkus-maven:19.2.0.1 AS build

# Copy local source
COPY . /project
WORKDIR /project

# Build jar and use JLink to create new distilled JRE
RUN ./gradlew buildNative -b build-quarkus.gradle --docker-build=true

RUN ls -l

## Stage 2 : Gradle build produces the application executable jar
# Alpine Linux
FROM alpine:latest

WORKDIR /work/

# Copy native image
COPY --from=build /project/build/*-runner /work/application

RUN chmod 775 /work

# Run native application 
CMD ["./application"]
