## Stage 1 : Build native image with Gradle + Quarkus + GraalVM

FROM quay.io/quarkus/ubi-quarkus-native-s2i:19.2.0.1 AS build

# Copy local source
WORKDIR /home/quarkus/source
COPY . /home/quarkus/source

# Allow read access for user
USER root
RUN chown -R quarkus /home/quarkus/source
USER quarkus

# Build jar and use JLink to create new distilled JRE
# RUN ./gradlew clean buildNative -b build-quarkus.gradle --info --stacktrace
#
# Blocking issue, ^^ this line above hangs on task buildNative:
#   "building native image"
#   "Running Quarkus native-image plugin on OpenJDK 64-Bit GraalVM CE 19.2.0.1"
# Cause appears to be Quarkus does not handle executable jars and CLI based
# applications. They are working on it: https://github.com/quarkusio/quarkus/issues/284

# Just use GraalVM's native-image compiler
RUN native-image -jar build/libs/listdir-0.1.0.jar


## Stage 2 : Place native app in small container
FROM alpine:latest

WORKDIR /work/

# Copy native app
COPY --from=build /tmp/ssl-libs/ /work/
COPY --from=build /home/quarkus/source/listdir-0.1.0 /work/listdir-0.1.0

RUN chmod 775 /work

# Run native app 
CMD ["./listdir-0.1.0"]
