FROM gradle:jdk12 as builder

COPY --chown=gradle:gradle . /home/gradle/src
WORKDIR /home/gradle/src
RUN gradle jar jlink --build-file build-jlink.gradle

RUN ls -R 

# Alpine Linux
FROM alpine

ENV JAVA_MINIMAL=/opt/jre
ENV PATH="$PATH:$JAVA_MINIMAL/bin"

COPY --from=builder /home/gradle/src/build/image "$JAVA_MINIMAL"
COPY --from=builder /home/gradle/src/build/libs/listdir-0.1.0.jar listdir.jar

# Run application using executable jar application 
CMD $JAVA_HOME/bin/java $JAVA_OPTS -jar listdir.jar
