## Stage 1 : build with maven builder image with native capabilities
# Alpine Linux with JDK

FROM quay.io/quarkus/ubi-quarkus-native-s2i:19.2.0.1 AS build
# FROM quay.io/quarkus/centos-quarkus-maven:19.2.0.1 AS build

# Copy local source
WORKDIR /home/quarkus/listdir
COPY . /home/quarkus/listdir

RUN pwd
RUN ls -l

USER root
RUN chown -R quarkus /home/quarkus/listdir
USER quarkus

# Build jar and use JLink to create new distilled JRE
RUN ./gradlew clean buildNative -b build-quarkus.gradle

RUN ls -l

## Stage 2 : Gradle build produces the application executable jar
FROM alpine:latest

WORKDIR /work/

# Copy native image
COPY --from=build /home/quarkus/listdir/build/*-runner /work/application

RUN chmod 775 /work

# Run native application 
CMD ["./application"]
