## Stage 1 : Build native image with GraalVM
FROM oracle/graalvm-ce:20.1.0-java11 as builder

RUN gu install native-image

WORKDIR /app
COPY . /app

RUN native-image -jar build/libs/listdir-0.1.0.jar

## Stage 2 : Place native app in small container
FROM frolvlad/alpine-glibc

# native-image only compiles to glibc, not Alpine's musl libc, so larger special Alpine is used
# TODO ^ can be done: https://jamesward.com/2020/05/07/graalvm-native-image-tips-tricks/

WORKDIR /work
COPY --from=builder /app/listdir-0.1.0 .
CMD ["./listdir-0.1.0"]
